services:
  - type: web
    name: plant-diagnosis-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python runtime/download_model.py && uvicorn main:app --host 0.0.0.0 --port $PORT

